// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PointOfSalesController from "./point_of_sales_controller.js"
application.register("point-of-sales", PointOfSalesController)

import ProductController from "./product_controller.js"
application.register("product", ProductController)

import StaffsController from "./staffs_controller.js"
application.register("staffs", StaffsController)

import ToastController from "./toast_controller.js"
application.register("toast", ToastController)

import WalletController from "./wallet_controller.js"
application.register("wallet", WalletController)

import CategoriesController from "./categories_controller.js"
application.register("categories", CategoriesController)

import ItemsCategoriesController from "./items_categories_controller.js"
application.register("item-categories", ItemsCategoriesController)

import ItemController from "./item_controller"
application.register('item', ItemController)

import NestedForm from 'stimulus-rails-nested-form'
application.register('nested-form', NestedForm)

import { Autocomplete } from 'stimulus-autocomplete'
application.register('autocomplete', Autocomplete)

import PasswordVisibility from 'stimulus-password-visibility'
application.register('password-visibility', PasswordVisibility)
